name: hemend_logger
description: log handler for logging package it will organize logging methods and easier to use
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
dependencies:
  logging: ">=1.0.0 <2.0.0"
  meta: ">=1.9.0 <2.0.0"
