name: hemend_logger
description: log handler for logging package it will organize logging methods and easier to use in the application
repository: https://github.com/FMotalleb/hemend_logger
version: 0.1.5+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  very_good_analysis: ^5.0.0
dependencies:
  logging: ">=1.0.0 <2.0.0"
  meta: ">=1.9.0 <2.0.0"
